include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    prefer_const_constructors: true
    avoid_print: false # se usa intencionalmente para logging de desarrollo en AudioManager
